source "http://rubygems.org"

gem 'rails',          '~>2.3.14'
gem 'json',           '>= 1.6.5'
                      
gem 'nokogiri',       '>= 1.4.4'
gem 'calais',         '>= 0.0.11'
gem 'rest-client',    '>= 1.0.3', :require => 'rest_client'
gem 'bcrypt-ruby',    '>= 2.1.2', :require => 'bcrypt'
gem 'rubyzip',        '>= 0.9.1', :require => 'zip/zip'
gem 'right_aws',      '>= 2.0.1'  # (Isn't) Our patched version (yet).
gem 'pg',             '>= 0.11.0'
gem 'jammit',         '>= 0.6.5'
gem 'docsplit',       '>= 0.6.3'
gem 'sunspot_rails',  '>= 1.3.3'
gem 'sunspot_solr',   '>= 1.3.3'
gem 'sunspot',        '~> 1.3.3'
gem 'fastercsv',      '>= 1.5.3'
gem 'sqlite3',        '~> 1.3.4'
gem 'passenger',      '~> 3.0.13'
gem 'sinatra',        '~> 0.9.4'
gem 'sanitize',       '~> 2.0.3'
gem 'rack',           '~> 1.1.3'
gem 'rdiscount',      '~> 1.6.8'
gem 'curb',           '~> 0.7.15'
gem 'daemons',        '~> 1.1.4'
gem 'cloud-crowd',    '~> 0.6.2'
gem 'yui-compressor', '~> 0.9.6'
gem 'thin',           '1.2.7'
